### ISSUE TITLE
Causes infinite loading screen and breaks the multiplequickslot bars mod

### ISSUE THREAD

**Issue by jellybeanmonster** [Faeryn/Outward_DualQuickSlots#2] opened 2022-07-15 22:23 UTC
Removing this mod allowed me to enter and exit town without infinite loading screens and allowed me to actually use the multiple quickslot bar mod without issue. I dont know why it just broke mid play through but the mod was working fine 2 hours into the game until i stared getting more gear then i noticed that a shield that i unequipped and disabled in the dual quickslot bar kept showing up in the dual quickslot menu which was a bug. The shield model still showed up in the dual quickslot menu even though i sold it to a merchant. Also i do have the latest version of the mod which said that it was given compatibility with the multiple quick slot bars which was version 1.0.1 which doesnt seem fix the issue with it breaking multiple quick slot bars.

**Comment by Faeryn** [comment] 2022-07-17 13:16
Please attach your log (Outward\Outward_Defed\output_log.txt). It may be caused by another mod due to the way the methods are patched.

**Comment by jellybeanmonster** [comment] 2022-07-21 00:25
i actually removed the mod from my modlist but i can show you all the mods i do have installed so maybe you can test for yourself because tbh i dont feel like playing outward rn. 
![image](https://user-images.githubusercontent.com/35231399/180104453-f215e60d-0e22-45f9-8d4b-a4c660a54f49.png)

![image](https://user-images.githubusercontent.com/35231399/180104471-2b33949e-a9b4-4b38-ae3c-130ec3012541.png)

![image](https://user-images.githubusercontent.com/35231399/180104485-b1f2167f-57e2-4264-bb55-cb996f479389.png)

**Comment by Faeryn** [comment] 2023-02-05 12:30
Item Price Helper is outdated and causes errors in DE, especially with certain mods such as this one. While it's generally not a good idea to use outdated mods, I will update mine to work with it.

**Comment by Faeryn** [comment] 2023-04-30 12:51
Closing it as the update probably fixed it (no more complaints).

**Closed as completed** 2023-04-30 12:52 UTC
Labels: bug
